# Generated by Django 2.2.11 on 2020-08-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('document', models.CharField(max_length=8)),
                ('cuil', models.CharField(max_length=13)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=15)),
                ('home', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=100)),
                ('province', models.CharField(default='Mendoza', max_length=100)),
                ('postal_code', models.CharField(max_length=4)),
                ('nationality', models.CharField(default='Argentino', max_length=100)),
                ('work', models.CharField(max_length=300)),
                ('work_address', models.CharField(max_length=400)),
                ('work_phone', models.CharField(max_length=15)),
                ('ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('foto_dni', models.ImageField(blank=True, null=True, upload_to='dni/')),
                ('email', models.EmailField(max_length=254)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('male_female', models.CharField(max_length=50)),
                ('client_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
