# Generated by Django 2.2.11 on 2020-08-17 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import loans.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('plan', models.IntegerField(default=0)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('produced', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('seller', models.CharField(blank=True, max_length=100, null=True)),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('commission_payment', models.DateTimeField()),
                ('payment_method', models.CharField(default='MUTUAL', max_length=100)),
                ('status', models.CharField(choices=[(loans.models.OrderStatus('CREATED'), 'CREATED'), (loans.models.OrderStatus('PAYED'), 'PAYED'), (loans.models.OrderStatus('LEGAL'), 'LEGAL')], default=loans.models.OrderStatus('CREATED'), max_length=50)),
                ('observations', models.CharField(max_length=500)),
                ('ending', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share', models.IntegerField(default=0)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('compensatory_interest', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('amortization', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('month_fee', models.CharField(max_length=50)),
                ('year_fee', models.CharField(max_length=50)),
                ('fee_payment', models.DateTimeField()),
                ('observations', models.CharField(max_length=500)),
                ('way_to_pay', models.CharField(max_length=100)),
                ('receipt', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.Loan')),
            ],
        ),
    ]
