# Generated by Django 2.2.11 on 2020-04-30 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import loans.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.CharField(max_length=100, unique=True)),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('plan', models.IntegerField(default=0)),
                ('produced', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('seller', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(default='MUTUAL', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[(loans.models.OrderStatus('CREATED'), 'CREATED'), (loans.models.OrderStatus('PAYED'), 'PAYED'), (loans.models.OrderStatus('LEGAL'), 'LEGAL')], default=loans.models.OrderStatus('CREATED'), max_length=50)),
                ('observations', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
