# Generated by Django 2.2.11 on 2020-08-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_auto_20200817_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.CharField(default='CREATED', max_length=50),
        ),
    ]
